export let data = [
  {
    key: "1",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0301",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["menunggu"],
    admin_name: "Rangga",
  },
  {
    key: "2",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0302",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["menunggu"],
    admin_name: "Rangga",
  },
  {
    key: "3",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0303",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["menunggu"],
    admin_name: "Rangga",
  },
  {
    key: "4",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0304",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "5",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0305",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "6",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0306",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "7",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0307",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "8",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0308",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "9",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0309",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "10",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0310",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "11",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0311",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "12",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0312",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "13",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0313",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "14",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0314",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
  {
    key: "15",
    uuid: "9baee3d8-a07c-409b-96ca-397d9aef0315",
    template_name: "order_confirmation",
    template_content: `Hello good morning {{1}} We would like to confirm your reservation about {{2}} Please confirm via this link {{3}}`,
    category: "ACCOUNT_UPDATE",
    language: "ID",
    media: "image",
    status: ["approve"],
    admin_name: "Rangga",
  },
];
