export let data = [
  {
    key: "1",
    id: 1,
    templateId: "TMPMMS-0001",
    platform: "MMS",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
  },
  {
    key: "2",
    id: 2,
    templateId: "TMPMMS-0002",
    platform: "MMS",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Kopi",
    mmsNameTemplate: "Template 2",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
  },
  {
    key: "3",
    id: 3,
    templateId: "TMPMMS-0003",
    platform: "MMS",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Pariwisata",
    mmsNameTemplate: "Template 3",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
  },
  {
    key: "4",
    id: 4,
    platform: "MMS",
    templateId: "TMPMMS-0004",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Kesehatan",
    mmsNameTemplate: "Template 4",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
  },
  {
    key: "5",
    id: 5,
    platform: "MMS",
    templateId: "TMPMMS-0005",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Pendidikan",
    mmsNameTemplate: "Template 5",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
  },
  {
    key: "6",
    id: 6,
    platform: "MMS",
    templateId: "TMPMMS-0006",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Electronik",
    mmsNameTemplate: "Template 6",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "7",
    id: 7,
    platform: "MMS",
    templateId: "TMPMMS-0001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "8",
    id: 8,
    platform: "MMS",
    templateId: "TMPMMS-0001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "9",
    id: 9,
    platform: "MMS",
    templateId: "TMPMMS-0001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "10",
    id: 10,
    platform: "MMS",
    templateId: "TMPMMS-0001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "11",
    id: 11,
    platform: "MMS",
    templateId: "TMPMMS-0001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
];
