export let data = [
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "2",
    templateId: "TMPMSG-000002",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Kopi",
    mmsNameTemplate: "Template 2",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "3",
    templateId: "TMPMSG-000003",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Pariwisata",
    mmsNameTemplate: "Template 3",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "4",
    templateId: "TMPMSG-000004",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Kesehatan",
    mmsNameTemplate: "Template 4",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "5",
    templateId: "TMPMSG-000005",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Pendidikan",
    mmsNameTemplate: "Template 5",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "6",
    templateId: "TMPMSG-000006",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Electronik",
    mmsNameTemplate: "Template 6",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
  {
    key: "1",
    templateId: "TMPMSG-000001",
    mmsTypeTemplate: "Static",
    mmsCategoryTemplate: "Olahraga",
    mmsNameTemplate: "Template 1",
    mmsCreatorAdminName: "John Brown",
    kontenTemplate:
      "hai semua pengguna setia Indosat kami akan bekerja sama dengan Praxis Academy membuka kesempatan untuk bergabung bersama kami.",
    date: "8/11/2021",
    status: ["waiting to approve"],
    verifikator: "-",
  },
];
